Packaging: improve subsystem packaging
git-svn-id: file:///home/code/svn/ovd/trunk@3872 2b2718be-6ee5-4ec5-ad1a-3fa14f9c7ca3

diff --git a/packaging/debian/ovd-subsystem/lucid/ulteo-ovd-subsystem.postinst b/packaging/debian/ovd-subsystem/lucid/ulteo-ovd-subsystem.postinst
--- a/packaging/debian/ovd-subsystem/lucid/ulteo-ovd-subsystem.postinst
+++ b/packaging/debian/ovd-subsystem/lucid/ulteo-ovd-subsystem.postinst
@@ -21,11 +21,46 @@ set_conf () {
     fi
 }
 
-set_host_conf () {
-    set_conf $HOSTCONF "CHROOT" $CHROOTPATH
-}
+# download the chroot if needed
+if [ ! -e "$CHROOTCONF" ] && ([ -z "$2" ] || [ -n "$DEBCONF_RECONFIGURE" ]); then
+    echo "Retrieving and uncompressing the chroot tarball..."
 
-set_tz () {
+    while true; do
+        db_get ulteo-ovd-subsystem/tarball_uri || true
+        if [ -n "$RET" ]; then
+            case "$RET" in
+                # curl needs file://, make sure we have it if we deal with a file path
+                /*)
+                    URI="file://$RET"
+                    ;;
+                *)
+                    URI="$RET"
+                    ;;
+            esac
+        else
+            break
+        fi
+
+        mkdir -p "$CHROOTPATH"
+
+        DOWNLOAD_OK="yes"
+        CURLOPTS="--retry 3 --connect-timeout 60 --insecure"
+        curl $CURLOPTS -f -s -I "$URI" || DOWNLOAD_OK="no"
+        if [ "$DOWNLOAD_OK" = "yes" ]; then
+            curl $CURLOPTS "$URI" | tar zx --numeric-owner -p -s -C "$CHROOTPATH" -f - && break
+        fi
+
+        # the chroot download failed
+        db_input critical ulteo-ovd-subsystem/download_error || true
+        db_go
+        db_fset ulteo-ovd-subsystem/tarball_uri seen false || true
+        db_input high ulteo-ovd-subsystem/tarball_uri || true
+        db_go
+    done
+
+    [ -n $HTTPPASSWD ] && unset HTTPPASSWD
+
+    # set timezone
     if [ -f /etc/timezone ]; then
         HOSTTZ=$(head -n 1 /etc/timezone)
     fi
@@ -33,59 +68,18 @@ set_tz () {
         cp /usr/share/zoneinfo/$HOSTTZ $CHROOTPATH/etc/localtime
         echo "$HOSTTZ" > $CHROOTPATH/etc/timezone
     fi
-}
-
-# download the chroot if needed
-if [ ! -e "$CHROOTCONF" ] && ([ -z "$2" ] || [ -n "$DEBCONF_RECONFIGURE" ]); then
-    db_get ulteo-ovd-subsystem/sm_address || true
-    SM="$RET"
-    URI="https://$SM/sessionmanager/base.tar.gz"
-
-    db_get ulteo-ovd-subsystem/tarball_uri || true
-    if [ -n "$RET" ]; then
-        case "$RET" in
-            # curl needs file://, make sure we have it if we deal with a file path
-            /*)
-                URI="file://$RET"
-                ;;
-            *)
-                URI="$RET"
-                ;;
-        esac
-    fi
-    echo "Retrieving and uncompressing the chroot tarball..."
-
-    mkdir -p "$CHROOTPATH"
-
-    DOWNLOAD_OK="yes"
-    CURLOPTS="--retry 3 --connect-timeout 60 --insecure"
-    curl $CURLOPTS -f -s -I "$URI" || DOWNLOAD_OK="no"
-    if [ "$DOWNLOAD_OK" = "yes" ]; then
-        curl $CURLOPTS "$URI" | tar zx --numeric-owner -p -s -C "$CHROOTPATH" -f - || DOWNLOAD_OK="no"
-    fi
-    [ -n $HTTPPASSWD ] && unset HTTPPASSWD
-
-    if [ "$DOWNLOAD_OK" = "no" ]; then
-        db_input ulteo-ovd-subsystem/download_error
-        db_go
-        exit 0
-    else
-        set_tz
-    fi
 fi
 
 # if we reinstall the ApS and the chroot is already there, the configs need to
 # be written again
 if [ ! -e $CHROOTCONF ]; then
-    echo "Warning: the chroot configuration file is missing, the configuration will have"
-    echo "         to be done manually in $CHROOTCONF."
+    db_input high ulteo-ovd-subsystem/no_chroot_conf || true
 else
     set_conf $CHROOTCONF "ROLES" "aps"
     set_conf $CHROOTCONF "LOG_LEVEL" "warn error info debug"
 
     # session manager url
-    db_get ulteo-ovd-subsystem/sm_address || true
-    URL="$RET"
+    db_get ulteo-ovd-subsystem/sm_address && URL="$RET"
     set_conf $CHROOTCONF "session_manager" "$URL"
 
     # resolv.conf
@@ -93,7 +87,7 @@ else
     [ -f /etc/hosts ] && cp /etc/hosts $CHROOTPATH/etc/hosts
 fi
 
-set_host_conf
+set_conf $HOSTCONF "CHROOT" $CHROOTPATH
 
 db_stop
 
diff --git a/packaging/debian/ovd-subsystem/squeeze/ulteo-ovd-subsystem.postinst b/packaging/debian/ovd-subsystem/squeeze/ulteo-ovd-subsystem.postinst
--- a/packaging/debian/ovd-subsystem/squeeze/ulteo-ovd-subsystem.postinst
+++ b/packaging/debian/ovd-subsystem/squeeze/ulteo-ovd-subsystem.postinst
@@ -21,28 +21,46 @@ set_conf () {
     fi
 }
 
-set_host_conf () {
-    set_conf $HOSTCONF "CHROOT" $CHROOTPATH
-}
+# download the chroot if needed
+if [ ! -e "$CHROOTCONF" ] && ([ -z "$2" ] || [ -n "$DEBCONF_RECONFIGURE" ]); then
+    echo "Retrieving and uncompressing the chroot tarball..."
 
-set_chroot_conf () {
+    while true; do
+        db_get ulteo-ovd-subsystem/tarball_uri || true
+        if [ -n "$RET" ]; then
+            case "$RET" in
+                # curl needs file://, make sure we have it if we deal with a file path
+                /*)
+                    URI="file://$RET"
+                    ;;
+                *)
+                    URI="$RET"
+                    ;;
+            esac
+        else
+            break
+        fi
 
-    set_conf $CHROOTCONF "ROLES" "aps"
-    set_conf $CHROOTCONF "LOG_LEVEL" "warn error info debug"
+        mkdir -p "$CHROOTPATH"
 
-    # session manager url
-    db_get ulteo-ovd-subsystem/sm_address || true
-    URL="$RET"
-    set_conf $CHROOTCONF "session_manager" "$URL"
+        DOWNLOAD_OK="yes"
+        CURLOPTS="--retry 3 --connect-timeout 60 --insecure"
+        curl $CURLOPTS -f -s -I "$URI" || DOWNLOAD_OK="no"
+        if [ "$DOWNLOAD_OK" = "yes" ]; then
+            curl $CURLOPTS "$URI" | tar zx --numeric-owner -p -s -C "$CHROOTPATH" -f - && break
+        fi
 
-    # resolv.conf
-    [ -f /etc/resolv.conf ] && cp /etc/resolv.conf \
-        $CHROOTPATH/etc/resolv.conf
-    [ -f /etc/hosts ] && cp /etc/hosts \
-        $CHROOTPATH/etc/hosts
-}
+        # the chroot download failed
+        db_input critical ulteo-ovd-subsystem/download_error || true
+        db_go
+        db_fset ulteo-ovd-subsystem/tarball_uri seen false || true
+        db_input high ulteo-ovd-subsystem/tarball_uri || true
+        db_go
+    done
 
-set_tz () {
+    [ -n $HTTPPASSWD ] && unset HTTPPASSWD
+
+    # set timezone
     if [ -f /etc/timezone ]; then
         HOSTTZ=$(head -n 1 /etc/timezone)
     fi
@@ -50,57 +68,26 @@ set_tz () {
         cp /usr/share/zoneinfo/$HOSTTZ $CHROOTPATH/etc/localtime
         echo "$HOSTTZ" > $CHROOTPATH/etc/timezone
     fi
-}
-
-# download the chroot if needed
-if [ ! -e "$CHROOTCONF" ] && ([ -z "$2" ] || [ -n "$DEBCONF_RECONFIGURE" ]); then
-    db_get ulteo-ovd-subsystem/sm_address || true
-    SM="$RET"
-    URI="https://$SM/sessionmanager/base.tar.gz"
-
-    db_get ulteo-ovd-subsystem/tarball_uri || true
-    if [ -n "$RET" ]; then
-        case "$RET" in
-            # curl needs file://, make sure we have it if we deal with a file path
-            /*)
-                URI="file://$RET"
-                ;;
-            *)
-                URI="$RET"
-                ;;
-        esac
-    fi
-    echo "Retrieving and uncompressing the chroot tarball..."
-
-    mkdir -p "$CHROOTPATH"
-
-    DOWNLOAD_OK="yes"
-    CURLOPTS="--retry 3 --connect-timeout 60 --insecure"
-    curl $CURLOPTS -f -s -I "$URI" || DOWNLOAD_OK="no"
-    if [ "$DOWNLOAD_OK" = "yes" ]; then
-        curl $CURLOPTS "$URI" | tar zx --numeric-owner -p -s -C "$CHROOTPATH" -f - || DOWNLOAD_OK="no"
-    fi
-    [ -n $HTTPPASSWD ] && unset HTTPPASSWD
-
-    if [ "$DOWNLOAD_OK" = "no" ]; then
-        echo "An error occured while downloading and installing the chroot, the server is not ready to be used."
-        echo "You can either reconfigure this package or use the aps-chroot-install script to set up the server."
-        exit 0
-    else
-        set_tz
-    fi
 fi
 
 # if we reinstall the ApS and the chroot is already there, the configs need to
 # be written again
 if [ ! -e $CHROOTCONF ]; then
-    echo "Warning: the chroot configuration file is missing, the configuration will have"
-    echo "         to be done manually in $CHROOTCONF."
+    db_input high ulteo-ovd-subsystem/no_chroot_conf || true
 else
-    set_chroot_conf
+    set_conf $CHROOTCONF "ROLES" "aps"
+    set_conf $CHROOTCONF "LOG_LEVEL" "warn error info debug"
+
+    # session manager url
+    db_get ulteo-ovd-subsystem/sm_address && URL="$RET"
+    set_conf $CHROOTCONF "session_manager" "$URL"
+
+    # resolv.conf
+    [ -f /etc/resolv.conf ] && cp /etc/resolv.conf $CHROOTPATH/etc/resolv.conf
+    [ -f /etc/hosts ] && cp /etc/hosts $CHROOTPATH/etc/hosts
 fi
 
-set_host_conf
+set_conf $HOSTCONF "CHROOT" $CHROOTPATH
 
 db_stop
 
