Packaging: improve postinst scripts (remove mysql configuration in session-manager)
git-svn-id: file:///home/code/svn/ovd/trunk@3918 2b2718be-6ee5-4ec5-ad1a-3fa14f9c7ca3

diff --git a/packaging/debian/ovd-session-manager/lenny/ulteo-ovd-session-manager.postinst b/packaging/debian/ovd-session-manager/lenny/ulteo-ovd-session-manager.postinst
--- a/packaging/debian/ovd-session-manager/lenny/ulteo-ovd-session-manager.postinst
+++ b/packaging/debian/ovd-session-manager/lenny/ulteo-ovd-session-manager.postinst
@@ -25,7 +25,7 @@ if [ ! -e $A2SITESDIR/sessionmanager-vhost-ssl ]; then
         # Bad /etc/hosts configuration
         serverName=$(hostname)
     fi
-    
+
     sed -i -r "s/^( *ServerName).*$/\1 ${serverName}/" \
         $CONFDIR/apache2-vhost-ssl.conf
     ln -s /etc/ulteo/sessionmanager/apache2-vhost-ssl.conf \
@@ -68,91 +68,63 @@ else
     echo "Your apache2 configuration is broken, so we're not restarting it for you."
 fi
 
-###############################################################################
+############################ / APACHE CONFIGURATION ############################
 
-# exit if we're not installing
+# only during the first install
 if [ "$1" != "configure" ] || ([ -n "$2" ] && [ -z "$DEBCONF_RECONFIGURE" ]); then
-    db_stop
-    exit 0
-fi
 
-gen_conf()
-{
-    db_get ulteo-ovd-session-manager/admin_login || true
-    LOGIN="$RET"
-    db_get ulteo-ovd-session-manager/admin_password || true
+    # set the configuration
+    CONFFILE=$CONFDIR/config.inc.php
+    db_get ulteo-ovd-session-manager/admin_login && LOGIN="$RET"
+    db_get ulteo-ovd-session-manager/admin_password
     PASSWD=$(echo -n $RET | md5sum | cut -d " " -f 1)
+    sed -r -i "s,^(.*SESSIONMANAGER_ADMIN_LOGIN.*').*('.*)$,\1$LOGIN\2," $CONFFILE
+    sed -r -i "s,^(.*SESSIONMANAGER_ADMIN_PASSWORD.*').*('.*)$,\1$PASSWD\2," $CONFFILE
+
     # clear the password
     unset RET
     db_reset ulteo-ovd-session-manager/admin_password
     db_reset ulteo-ovd-session-manager/admin_password_again
 
-    CONFFILE=$CONFDIR/config.inc.php
-    sed -r -i "s,^(.*SESSIONMANAGER_ADMIN_LOGIN.*').*('.*)$,\1$LOGIN\2," $CONFFILE
-    sed -r -i "s,^(.*SESSIONMANAGER_ADMIN_PASSWORD.*').*('.*)$,\1$PASSWD\2," $CONFFILE
-
+    # change conffile permission
     if ! dpkg-statoverride --list $CONFFILE >/dev/null 2>&1; then
         dpkg-statoverride --update --add www-data www-data 0660 $CONFFILE
     fi
-}
 
-mysql_config()
-{
-    db_get ulteo-ovd-session-manager/mysql_setup || true
-    [ "$RET" != "true" ] && return
+    # download the chroot if needed
+    while [ ! -e "$CHROOT_TARGET" ]; do
 
-    # let's configure mysql
-    db_get ulteo-ovd-session-manager/mysql_dbserver
-    dbserver=$RET
-    db_get ulteo-ovd-session-manager/mysql_dbadmin
-    dbadmin=$RET
-    db_get ulteo-ovd-session-manager/mysql_dbadmpass
-    dbadmpass=$RET
-    db_reset ulteo-ovd-session-manager/mysql_dbadmpass
-    db_get ulteo-ovd-session-manager/mysql_dbname
-    dbname=$RET
-    db_get ulteo-ovd-session-manager/mysql_dbuser
-    dbuser=$RET
-    db_get ulteo-ovd-session-manager/mysql_dbpass
-    dbpass=$RET
-    db_reset ulteo-ovd-session-manager/mysql_dbpass
+        # get the tarball url and quit if empty
+        db_get ulteo-ovd-session-manager/tarball_url && URL=$RET
+        [ -z $URL ] && break
 
-    # create the database
-    . /usr/share/wwwconfig-common/mysql-createdb.sh
-    # create user
-    . /usr/share/wwwconfig-common/mysql-createuser.sh
-
-    php /usr/share/ulteo/sessionmanager/admin/init/setup.php \
-        "$dbserver" "$dbname" ulteo_ "$dbuser" "$dbpass" 2> /dev/null
-}
-
-# set the configuration if we install
-gen_conf
-
-# get the chroot
-db_get ulteo-ovd-session-manager/download_tarball || true
-URL="$RET"
-if [ ! -e $CHROOT_TARGET ]; then
-	if [ x"$URL" != x"" ]; then
-        CURLOPTS="--retry 3 --connect-timeout 60  --insecure -L"
-    	if ! curl $CURLOPTS -f "$URL" > $CHROOT_TARGET; then
-            rm -f $CHROOT_TARGET
-            echo "Unable to retrieve the chroot archive."
-            echo "You need to download it manually as $CHROOT_TARGET, or use the 'sm-config' script."
+        # get the chroot
+        CURLOPTS="--retry 3 --connect-timeout 60 --insecure"
+        if curl $CURLOPTS -f -s -I "$URL" ; then
+            echo "Retrieving the chroot tarball..."
+            curl $CURLOPTS "$URL" > $CHROOT_TARGET && continue
         fi
-	fi
+
+        # chroot download failed
+        rm -f $CHROOT_TARGET
+        db_input critical ulteo-ovd-session-manager/download_error || true
+        db_go
+        db_fset ulteo-session-manager/tarball_url seen false || true
+        db_input high ulteo-ovd-session-manager/tarball_url || true
+        db_go
+    done
+
+    # change log and spool file permissions
+    for f in /var/spool/ulteo/sessionmanager /var/log/ulteo/sessionmanager; do
+        if ! dpkg-statoverride --list $f >/dev/null 2>&1; then
+            dpkg-statoverride --update --add www-data www-data 0770 $f
+        fi
+    done
+
+    # make sure that the data created by the postinst are owned by www-data
+    chown -R www-data:www-data /var/spool/ulteo/sessionmanager \
+                               /var/log/ulteo/sessionmanager
 fi
-
-mysql_config
-
-for f in /var/spool/ulteo/sessionmanager /var/log/ulteo/sessionmanager; do
-    if ! dpkg-statoverride --list $f >/dev/null 2>&1; then
-        dpkg-statoverride --update --add www-data www-data 0770 $f
-    fi
-done
-
-# make sure that the data created by the postinst are owned by www-data
-chown -R www-data:www-data /var/spool/ulteo/sessionmanager /var/log/ulteo/sessionmanager
 
 db_stop
 
diff --git a/packaging/debian/ovd-session-manager/lucid/ulteo-ovd-session-manager.postinst b/packaging/debian/ovd-session-manager/lucid/ulteo-ovd-session-manager.postinst
--- a/packaging/debian/ovd-session-manager/lucid/ulteo-ovd-session-manager.postinst
+++ b/packaging/debian/ovd-session-manager/lucid/ulteo-ovd-session-manager.postinst
@@ -70,54 +70,61 @@ fi
 
 ############################ / APACHE CONFIGURATION ############################
 
-# exit if we're not installing
+# only during the first install
 if [ "$1" != "configure" ] || ([ -n "$2" ] && [ -z "$DEBCONF_RECONFIGURE" ]); then
-    db_stop
-    exit 0
-fi
 
-# set the configuration
-CONFFILE=$CONFDIR/config.inc.php
-db_get ulteo-ovd-session-manager/admin_login || true
-LOGIN="$RET"
-db_get ulteo-ovd-session-manager/admin_password || true
-PASSWD=$(echo -n $RET | md5sum | cut -d " " -f 1)
-sed -r -i "s,^(.*SESSIONMANAGER_ADMIN_LOGIN.*').*('.*)$,\1$LOGIN\2," $CONFFILE
-sed -r -i "s,^(.*SESSIONMANAGER_ADMIN_PASSWORD.*').*('.*)$,\1$PASSWD\2," $CONFFILE
+    # set the configuration
+    CONFFILE=$CONFDIR/config.inc.php
+    db_get ulteo-ovd-session-manager/admin_login && LOGIN="$RET"
+    db_get ulteo-ovd-session-manager/admin_password
+    PASSWD=$(echo -n $RET | md5sum | cut -d " " -f 1)
+    sed -r -i "s,^(.*SESSIONMANAGER_ADMIN_LOGIN.*').*('.*)$,\1$LOGIN\2," $CONFFILE
+    sed -r -i "s,^(.*SESSIONMANAGER_ADMIN_PASSWORD.*').*('.*)$,\1$PASSWD\2," $CONFFILE
 
-# clear the password
-unset RET
-db_reset ulteo-ovd-session-manager/admin_password
-db_reset ulteo-ovd-session-manager/admin_password_again
+    # clear the password
+    unset RET
+    db_reset ulteo-ovd-session-manager/admin_password
+    db_reset ulteo-ovd-session-manager/admin_password_again
 
-# change conffile permission
-if ! dpkg-statoverride --list $CONFFILE >/dev/null 2>&1; then
-    dpkg-statoverride --update --add www-data www-data 0660 $CONFFILE
-fi
-
-# get the chroot
-db_get ulteo-ovd-session-manager/download_tarball || true
-URL="$RET"
-if [ ! -e $CHROOT_TARGET ]; then
-	if [ x"$URL" != x"" ]; then
-        CURLOPTS="--retry 3 --connect-timeout 60  --insecure -L"
-    	if ! curl $CURLOPTS -f "$URL" > $CHROOT_TARGET; then
-            rm -f $CHROOT_TARGET
-            echo "Unable to retrieve the chroot archive."
-            echo "You need to download it manually as $CHROOT_TARGET, or use the 'sm-config' script."
-        fi
-	fi
-fi
-
-# change log and spool file permissions
-for f in /var/spool/ulteo/sessionmanager /var/log/ulteo/sessionmanager; do
-    if ! dpkg-statoverride --list $f >/dev/null 2>&1; then
-        dpkg-statoverride --update --add www-data www-data 0770 $f
+    # change conffile permission
+    if ! dpkg-statoverride --list $CONFFILE >/dev/null 2>&1; then
+        dpkg-statoverride --update --add www-data www-data 0660 $CONFFILE
     fi
-done
 
-# make sure that the data created by the postinst are owned by www-data
-chown -R www-data:www-data /var/spool/ulteo/sessionmanager /var/log/ulteo/sessionmanager
+    # download the chroot if needed
+    while [ ! -e "$CHROOT_TARGET" ]; do
+
+        # get the tarball url and quit if empty
+        db_get ulteo-ovd-session-manager/tarball_url && URL=$RET
+        [ -z $URL ] && break
+
+        # get the chroot
+        CURLOPTS="--retry 3 --connect-timeout 60 --insecure"
+        if curl $CURLOPTS -f -s -I "$URL" ; then
+            echo "Retrieving the chroot tarball..."
+            curl $CURLOPTS "$URL" > $CHROOT_TARGET && continue
+        fi
+
+        # chroot download failed
+        rm -f $CHROOT_TARGET
+        db_input critical ulteo-ovd-session-manager/download_error || true
+        db_go
+        db_fset ulteo-session-manager/tarball_url seen false || true
+        db_input high ulteo-ovd-session-manager/tarball_url || true
+        db_go
+    done
+
+    # change log and spool file permissions
+    for f in /var/spool/ulteo/sessionmanager /var/log/ulteo/sessionmanager; do
+        if ! dpkg-statoverride --list $f >/dev/null 2>&1; then
+            dpkg-statoverride --update --add www-data www-data 0770 $f
+        fi
+    done
+
+    # make sure that the data created by the postinst are owned by www-data
+    chown -R www-data:www-data /var/spool/ulteo/sessionmanager \
+                               /var/log/ulteo/sessionmanager
+fi
 
 db_stop
 
diff --git a/packaging/debian/ovd-subsystem/lenny/ulteo-ovd-subsystem.postinst b/packaging/debian/ovd-subsystem/lenny/ulteo-ovd-subsystem.postinst
--- a/packaging/debian/ovd-subsystem/lenny/ulteo-ovd-subsystem.postinst
+++ b/packaging/debian/ovd-subsystem/lenny/ulteo-ovd-subsystem.postinst
@@ -18,43 +18,33 @@ set_conf () {
 }
 
 # download the chroot if needed
-if [ ! -e "$CHROOTCONF" ]; then
-    echo "Retrieving and uncompressing the chroot tarball..."
+while [ ! -e "$CHROOTCONF" ]; do
 
-    while true; do
-        db_get ulteo-ovd-subsystem/tarball_uri || true
-        if [ -n "$RET" ]; then
-            case "$RET" in
-                # curl needs file://, make sure we have it if we deal with a file path
-                /*)
-                    URI="file://$RET"
-                    ;;
-                *)
-                    URI="$RET"
-                    ;;
-            esac
-        else
-            break
-        fi
+    # get the tarball uri and quit if empty
+    db_get ulteo-ovd-subsystem/tarball_uri && URI=$RET
+    [ -z $URI ] && break
 
+    # curl needs file://, make sure we have it if we deal with a file path
+    [ $(echo $URI | cut -c 1) = '/' ] && URI="file://$URI"
+
+    # get the chroot
+    CURLOPTS="--retry 3 --connect-timeout 60 --insecure"
+    if curl $CURLOPTS -f -s -I "$URI" ; then
+        echo "Retrieving and uncompressing the chroot tarball..."
         mkdir -p "$CHROOTPATH"
+        curl $CURLOPTS "$URI" | tar zx --numeric-owner -p -s -C "$CHROOTPATH" -f - && continue
+    fi
 
-        DOWNLOAD_OK="yes"
-        CURLOPTS="--retry 3 --connect-timeout 60 --insecure"
-        curl $CURLOPTS -f -s -I "$URI" || DOWNLOAD_OK="no"
-        if [ "$DOWNLOAD_OK" = "yes" ]; then
-            curl $CURLOPTS "$URI" | tar zx --numeric-owner -p -s -C "$CHROOTPATH" -f - && break
-        fi
+    # chroot download failed
+    rm -rf $CHROOTPATH
+    db_input critical ulteo-ovd-subsystem/download_error || true
+    db_go
+    db_fset ulteo-ovd-subsystem/tarball_uri seen false || true
+    db_input high ulteo-ovd-subsystem/tarball_uri || true
+    db_go
+done
 
-        # the chroot download failed
-        db_input critical ulteo-ovd-subsystem/download_error || true
-        db_go
-        db_fset ulteo-ovd-subsystem/tarball_uri seen false || true
-        db_input high ulteo-ovd-subsystem/tarball_uri || true
-        db_go
-    done
-
-    [ -n $HTTPPASSWD ] && unset HTTPPASSWD
+if [ ! -e "$CHROOTCONF" ]; then
 
     # set timezone
     if [ -f /etc/timezone ]; then
@@ -64,11 +54,9 @@ if [ ! -e "$CHROOTCONF" ]; then
         cp /usr/share/zoneinfo/$HOSTTZ $CHROOTPATH/etc/localtime
         echo "$HOSTTZ" > $CHROOTPATH/etc/timezone
     fi
-fi
 
-# if we reinstall the ApS and the chroot is already there, the configs need to
-# be written again
-if [ -e $CHROOTCONF ]; then
+    # if we reinstall the ApS and the chroot is already there, the configs need to
+    # be written again
     set_conf $CHROOTCONF "ROLES" "aps"
     set_conf $CHROOTCONF "LOG_LEVEL" "warn error info debug"
 
@@ -79,11 +67,11 @@ if [ -e $CHROOTCONF ]; then
     # resolv.conf
     [ -f /etc/resolv.conf ] && cp /etc/resolv.conf $CHROOTPATH/etc/resolv.conf
     [ -f /etc/hosts ] && cp /etc/hosts $CHROOTPATH/etc/hosts
+
+    set_conf $HOSTCONF "CHROOT" $CHROOTPATH
 else
     db_input high ulteo-ovd-subsystem/no_chroot_conf || true
 fi
-
-set_conf $HOSTCONF "CHROOT" $CHROOTPATH
 
 db_stop
 
