Improvement: test in uchroot if some conf options are empty
git-svn-id: file:///home/code/svn/ovd/trunk@7482 2b2718be-6ee5-4ec5-ad1a-3fa14f9c7ca3

diff --git a/Subsystem/script/uchroot b/Subsystem/script/uchroot
--- a/Subsystem/script/uchroot
+++ b/Subsystem/script/uchroot
@@ -27,4 +27,9 @@ else
 fi
 [ -f /etc/ulteo/subsystem.conf ] && . /etc/ulteo/subsystem.conf
 
+if [ -z "$CHROOTLANG" -o -z "$CHROOTDIR" ]; then
+    echo "required option with empty value" >&2
+    exit 126
+fi
+
 env LANG=$CHROOTLANG LC_ALL=$CHROOTLANG chroot $CHROOTDIR $*
