* typos * B-D on po-debconf * fix postinst:   - set correct permissions   - make dpkg-reconfigure work
git-svn-id: file:///home/code/svn/ovd/trunk@269 2b2718be-6ee5-4ec5-ad1a-3fa14f9c7ca3

diff --git a/debian/ovd-session-manager/debian/postinst b/debian/ovd-session-manager/debian/postinst
--- a/debian/ovd-session-manager/debian/postinst
+++ b/debian/ovd-session-manager/debian/postinst
@@ -2,7 +2,8 @@
 
 . /usr/share/debconf/confmodule
 
-if [ "$1" != "configure" ]; then
+# Do nothing if we're not installing
+if [ "$1" != "configure" ] || ([ -n "$2" ] && [ -z "$DEBCONF_RECONFIGURE" ]); then
     exit 0
 fi
 
@@ -39,24 +40,20 @@ gen_conf()
     sed -r -i "s,^(.*SESSIONMANAGER_ADMIN_PASSWORD.*').*('.*)$,\1$PASSWD\2," $CONFFILE
 }
 
-# set the fqdns if the conffile doesn't exist already
-if [ ! -e $CONFFILE ]; then
-    gen_conf
+# set the configuration if we install
+gen_conf
+chown root:www-data $CONFFILE
+chmod 0640 $CONFFILE
 
-    # set permissions
-    mkdir -p /var/spool/ulteo/sessionmanager /var/log/ulteo/sessionmanager
-    chown root:www-data /var/spool/ulteo/sessionmanager /var/log/ulteo/sessionmanager
-    chmod 2770 /var/spool/ulteo/sessionmanager /var/log/ulteo/sessionmanager
-    chown root:www-data $CONFFILE
-    chmod 0640 $CONFFILE
-fi
+mkdir -p /var/spool/ulteo/sessionmanager /var/log/ulteo/sessionmanager
+chown root:www-data /var/spool/ulteo/sessionmanager /var/log/ulteo/sessionmanager
+chmod 2770 /var/spool/ulteo/sessionmanager /var/log/ulteo/sessionmanager
 
-if [ ! -e $CHROOT_TARGET ]; then
-    db_get od/sessionmanager/download_tarball || true
-    URL="$RET"
-    if [ x"$URL" != x"" ]; then
-        wget $WGETARGS $URL -O $CHROOT_TARGET || echo "Unable to retrieve the chroot archive. You need to download it manually as $CHROOT_TARGET"
-    fi
+# get the chroot
+db_get od/sessionmanager/download_tarball || true
+URL="$RET"
+if [ x"$URL" != x"" ]; then
+    wget $WGETARGS $URL -O $CHROOT_TARGET || echo "Unable to retrieve the chroot archive. You need to download it manually as $CHROOT_TARGET, or use the 'sm-config' script."
 fi
 
 apache_config
