ovd-session-manager (1.0~beta2-0ulteo1) ovd-polaris; urgency=low
  * Added debconf template entries to configure mysql database
  * Added postinst commands to create mysql database and user

  -- Daniele Favara <dfavara@ulteo.com>  Wed, 11 Feb 2009 13:22:29 +0000

git-svn-id: file:///home/code/svn/ovd/trunk@510 2b2718be-6ee5-4ec5-ad1a-3fa14f9c7ca3

diff --git a/debian/ovd-session-manager/debian/postinst b/debian/ovd-session-manager/debian/postinst
--- a/debian/ovd-session-manager/debian/postinst
+++ b/debian/ovd-session-manager/debian/postinst
@@ -38,7 +38,38 @@ gen_conf()
 
     sed -r -i "s,^(.*SESSIONMANAGER_ADMIN_LOGIN.*').*('.*)$,\1$LOGIN\2," $CONFFILE
     sed -r -i "s,^(.*SESSIONMANAGER_ADMIN_PASSWORD.*').*('.*)$,\1$PASSWD\2," $CONFFILE
+
+    # TODO : add mysql database config
 }
+
+# Configure Mysql Database
+db_get od/sessionmanager/mysql/configure
+    if [ "$RET" = true ]; then
+
+	# get the answers to our questions
+	db_get od/sessionmanager/mysql/dbserver
+	dbserver=$RET
+	db_get od/sessionmanager/mysql/dbadmin
+	dbadmin=$RET
+	db_get od/sessionmanager/mysql/dbadmpass
+	dbadmpass=$RET
+	db_reset od/sessionmanager/mysql/dbadmpass
+	db_get od/sessionmanager/mysql/dbname
+	dbname=$RET
+	db_get od/sessionmanager/mysql/dbuser
+	dbuser=$RET
+	db_get od/sessionmanager/mysql/dbpass
+	dbpass=$RET
+	db_reset od/sessionmanager/mysql/dbpass
+
+	# create the database
+	. /usr/share/wwwconfig-common/mysql-createdb.sh
+	# create user
+	. /usr/share/wwwconfig-common/mysql-createuser.sh
+    fi
+
+
+
 
 # set the configuration if we install
 gen_conf
@@ -52,8 +83,10 @@ chmod 2770 /var/spool/ulteo/sessionmanager /var/log/ulteo/sessionmanager
 # get the chroot
 db_get od/sessionmanager/download_tarball || true
 URL="$RET"
-if [ x"$URL" != x"" ]; then
-    wget $WGETARGS $URL -O $CHROOT_TARGET || echo "Unable to retrieve the chroot archive. You need to download it manually as $CHROOT_TARGET, or use the 'sm-config' script."
+if [ ! -e $CHROOT_TARGET ]; then
+	if [ x"$URL" != x"" ]; then
+    	wget $WGETARGS $URL -O $CHROOT_TARGET || echo "Unable to retrieve the chroot archive. You need to download it manually as $CHROOT_TARGET, or use the 'sm-config' script."
+	fi
 fi
 
 apache_config
