* typo * if the chroot download fails, make sure that no corrupted file has been   created (it would make the reconfiguration fail)
git-svn-id: file:///home/code/svn/ovd/trunk@1612 2b2718be-6ee5-4ec5-ad1a-3fa14f9c7ca3

diff --git a/debian/ovd-session-manager/debian/ulteo-ovd-session-manager.postinst b/debian/ovd-session-manager/debian/ulteo-ovd-session-manager.postinst
--- a/debian/ovd-session-manager/debian/ulteo-ovd-session-manager.postinst
+++ b/debian/ovd-session-manager/debian/ulteo-ovd-session-manager.postinst
@@ -81,7 +81,11 @@ db_get ulteo-ovd-session-manager/download_tarball || true
 URL="$RET"
 if [ ! -e $CHROOT_TARGET ]; then
 	if [ x"$URL" != x"" ]; then
-    	curl $CURLOPTS -f "$URI" > $CHROOT_TARGET || echo "Unable to retrieve the chroot archive. You need to download it manually as $CHROOT_TARGET, or use the 'sm-config' script."
+    	if ! curl $CURLOPTS -f "$URL" > $CHROOT_TARGET; then
+            rm -f $CHROOT_TARGET
+            echo "Unable to retrieve the chroot archive."
+            echo "You need to download it manually as $CHROOT_TARGET, or use the 'sm-config' script."
+        fi
 	fi
 fi
 
