Packaging: create two new packages (ulteo-ovd-slaveserver-role-aps and ulteo-ovd-slaveserver-role-fs)
git-svn-id: file:///home/code/svn/ovd/trunk@3256 2b2718be-6ee5-4ec5-ad1a-3fa14f9c7ca3

diff --git a/packaging/debian/ovd-slaveserver/debian/ulteo-ovd-slaveserver.postinst b/packaging/debian/ovd-slaveserver/debian/ulteo-ovd-slaveserver.postinst
--- a/packaging/debian/ovd-slaveserver/debian/ulteo-ovd-slaveserver.postinst
+++ b/packaging/debian/ovd-slaveserver/debian/ulteo-ovd-slaveserver.postinst
@@ -3,23 +3,16 @@
 . /usr/share/debconf/confmodule
 db_version 2.0
 
-# Do nothing if we're not installing
-if [ "$1" != "configure" ] || ([ -n "$2" ] && [ -z "$DEBCONF_RECONFIGURE" ]); then
-    exit 0
-fi
-
 CONFFILE="/etc/ulteo/ovd-slaveserver.conf"
 
-gen_conf()
-{
-    db_get ulteo-ovd-slaveserver/session_manager || true
-    SESSION_MANAGER="$RET"
-
-    sed -r -i "s,^(session_manager = )(.*)$,\1$SESSION_MANAGER," $CONFFILE
-}
+if [ ! -f $CONFFILE ]; then
+    echo "Config file $CONFFILE not found"
+    exit 1
+fi
 
 # set the configuration if we install
-gen_conf
+db_get ulteo-ovd-slaveserver/session_manager || true
+sed -i "s/^session_manager.*/session_manager = $RET/" $CONFFILE
 
 db_stop
 
