indentation cleanup
git-svn-id: file:///home/code/svn/ovd/trunk@1703 2b2718be-6ee5-4ec5-ad1a-3fa14f9c7ca3

diff --git a/ApplicationServer/daemon/ulteo-ovdd b/ApplicationServer/daemon/ulteo-ovdd
--- a/ApplicationServer/daemon/ulteo-ovdd
+++ b/ApplicationServer/daemon/ulteo-ovdd
@@ -26,15 +26,15 @@ system_clean() {
     local fail=0
 
     for user in $(get_real_user); do
-	log_INFO "system_clean: existing user '$user': deluser him"
-	deluser $user
-	if [ $? !=  0 ]; then
-	    log_ERROR "system_clean: unable to remove user '$user'"
-	    local fail=1
-	fi
+        log_INFO "system_clean: existing user '$user': deluser him"
+        deluser $user
+        if [ $? !=  0 ]; then
+            log_ERROR "system_clean: unable to remove user '$user'"
+            local fail=1
+        fi
     done
     [ $fail = 0 ] || return $fail
-    
+
     # Last, to ensure no user homes are left :
     do_clean
 }
@@ -53,16 +53,16 @@ system_set_broken() {
 check_cpulimit() {
     cache_ps_chroot_display | mawk '{ if ($3 > 25.0) print $1" "$2 }' |\
     while read i j; do
-	if cache_is_cpulimited $j; then
-	    log_DEBUG "process $j already cpulimited"
-	else
-	    k=`id -u $i 2>/dev/null`
+    if cache_is_cpulimited $j; then
+        log_DEBUG "process $j already cpulimited"
+    else
+        k=`id -u $i 2>/dev/null`
 
-	    if [ $? -eq 0 ] && [ $k -ge 1000 ]; then
-	        cpulimit -p $j -l 25 -z&
-	        log_INFO "limiting process $j"
-	    fi
-	fi
+        if [ $? -eq 0 ] && [ $k -ge 1000 ]; then
+            cpulimit -p $j -l 25 -z&
+            log_INFO "limiting process $j"
+        fi
+    fi
     done
 }
 
@@ -75,8 +75,8 @@ session_check_status() {
     SSH_USER="SSH$i"
 
     if [ ! -d $SESSID_DIR ]; then
-	log_ERROR "session_check_status: no such directory '$SESSID_DIR'"
-	return 1
+        log_ERROR "session_check_status: no such directory '$SESSID_DIR'"
+        return 1
     fi
 
     if [ $# -gt 1 ]; then
@@ -86,8 +86,8 @@ session_check_status() {
     fi
 
     if ! session_valid_runasap $RUNASAP; then
-	log_WARN "Unsupported runasap value for session $SESSID"
-	session_switch_status $SESSID 3
+        log_WARN "Unsupported runasap value for session $SESSID"
+        session_switch_status $SESSID 3
         session_check_status $SESSID 3
         return $?
     fi
@@ -96,12 +96,12 @@ session_check_status() {
     if [ $RUNASAP -eq 3 ]; then
         log_INFO "Killing Session $SESSID"
         session_purge ${SESSID}
-	return 1
+        return 1
     fi
 
     # If sesion is not initialize yet
     if [ $RUNASAP -eq 0 ]; then 
-	return 0
+        return 0
     fi
 
     NICK=`cat ${SESSID_DIR}/parameters/user_displayname`
@@ -118,87 +118,84 @@ session_check_status() {
 
     # If sesion need to be restore ...
     if [ $RUNASAP -eq 11 ]; then 
-	session_restore $SESSID
-	[ $? -ne 0 ] && return 1
+        session_restore $SESSID
+        [ $? -ne 0 ] && return 1
     fi
 
     # Check the timeout if the session is timetouted
     if [ -f ${SESSID_DIR}/private/running ] && [ -f ${SESSID_DIR}/parameters/timeout ]; then
-	EXPIRE=`cat ${SESSID_DIR}/parameters/timeout`
+        EXPIRE=`cat ${SESSID_DIR}/parameters/timeout`
 
-	let ct=$(( `date +%s` ))
-	let diff=$(( $ct - $EXPIRE ))
+        let ct=$(( `date +%s` ))
+        let diff=$(( $ct - $EXPIRE ))
 
-	if [ ! -f ${SESSID_DIR}/private/timeouted  ] && [ $diff -gt -180 ] && [ $DESKTOP_SESSION -gt 0 ]; then
-	   log_INFO "Session is going to expire in 3 minutes"
-	    export i SESSID_DIR SESSID
-	    timeout.sh &
-	    touch ${SESSID_DIR}/private/timeouted 
-	fi
+        if [ ! -f ${SESSID_DIR}/private/timeouted  ] && [ $diff -gt -180 ] && [ $DESKTOP_SESSION -gt 0 ]; then
+            log_INFO "Session is going to expire in 3 minutes"
+            export i SESSID_DIR SESSID
+            timeout.sh &
+            touch ${SESSID_DIR}/private/timeouted 
+        fi
 
-	if [ $diff -gt 0 ]; then
-	    log_INFO "Session expired => Timeout:$ct, EXPIRE:$EXPIRE, diff:$diff"
-	    session_switch_status $SESSID 3
+        if [ $diff -gt 0 ]; then
+            log_INFO "Session expired => Timeout:$ct, EXPIRE:$EXPIRE, diff:$diff"
+            session_switch_status $SESSID 3
             session_check_status $SESSID 3
             return $?
-	fi
+        fi
     fi
 
     # If sesion is in suspend mode ... Nothing to do
     if [ $RUNASAP -eq 9 ] || [ $RUNASAP -eq 10 ]; then 
-	return 0
+        return 0
     fi
 
     # if session owner has vanished, kill session (useful for shared sessions)
     KMA=${SESSID_DIR}/infos/keepmealive
     if [ -e $KMA ]; then
-	let ctg2=$(( `date +%s` ))
-	let candidate2=$(( `stat -c "%Z" $KMA` ))
-	let diffg2=$(( $ctg2 - $candidate2 ))
+        let ctg2=$(( `date +%s` ))
+        let candidate2=$(( `stat -c "%Z" $KMA` ))
+        let diffg2=$(( $ctg2 - $candidate2 ))
 
-	if [ $diffg2 -gt 20 ]; then
-	    log_WARN "KMA expired diff:$diffg2"
-	    # Suspend the session if the sesion was running and it's setup to suspend
-	    if [ -f ${SESSID_DIR}/private/running ] && [ -f ${SESSID_DIR}/parameters/persistent ]; then
-		session_suspend $SESSID
-		[ $? -eq 0 ] && return 0
-	    fi
-	    session_switch_status $SESSID 3
+        if [ $diffg2 -gt 20 ]; then
+            log_WARN "KMA expired diff:$diffg2"
+            # Suspend the session if the sesion was running and it's setup to suspend
+            if [ -f ${SESSID_DIR}/private/running ] && [ -f ${SESSID_DIR}/parameters/persistent ]; then
+                session_suspend $SESSID
+                [ $? -eq 0 ] && return 0
+            fi
+            session_switch_status $SESSID 3
             session_check_status $SESSID 3
             return $?
-	fi
+        fi
     fi
-
-	   
-
 
     #
     # SWITCH CASE runasap
     #
- 
+
     # session to launch? launch it! (runasap == 1)
     if [ $RUNASAP -eq 1 ]; then
-	webservices_session_request $SESSID 1
-	log_INFO "RUNASAP 1 for $SESSID..."
+        webservices_session_request $SESSID 1
+        log_INFO "RUNASAP 1 for $SESSID..."
 
-	if [ "$NICK" = "" ]; then
-	    log_ERROR "NULL nickname 2 "$NICK
-	    return 1
-	fi
+        if [ "$NICK" = "" ]; then
+            log_ERROR "NULL nickname 2 "$NICK
+            return 1
+        fi
 
-	# If the user login is root or dbus or 
-	# anything already exist, we change it
-	session_change_login_if_needed || \
-	    USER_LOGIN=`cat ${SESSID_DIR}/parameters/user_login`
+        # If the user login is root or dbus or 
+        # anything already exist, we change it
+        session_change_login_if_needed || \
+            USER_LOGIN=`cat ${SESSID_DIR}/parameters/user_login`
 
 
-	USER_HOME=/home/$NICK
-	echo $NICK > /tmp/VNC$i
+        USER_HOME=/home/$NICK
+        echo $NICK > /tmp/VNC$i
 
-	log_INFO "ulteo-ovd runasap1, nickname: '$NICK', USER_HOME:'$USER_HOME'"
+        log_INFO "ulteo-ovd runasap1, nickname: '$NICK', USER_HOME:'$USER_HOME'"
 
-	session_switch_status $SESSID 22
-	RUNASAP=22
+        session_switch_status $SESSID 22
+        RUNASAP=22
 
         set_user_env.sh $SESSID
         if [  $? -ne 0 ]; then
@@ -214,7 +211,7 @@ session_check_status() {
             sleep 0.5
         fi
 
-	return 0
+        return 0
 
     elif [ $RUNASAP -eq 2 ]; then
         # if the owner_exit file exist, kill the session
@@ -222,8 +219,8 @@ session_check_status() {
             log_INFO "Owner exit"
             # Suspend the session if the sesion was running and it's setup to suspend
             if [ -f ${SESSID_DIR}/private/running ] && [ -f ${SESSID_DIR}/parameters/persistent ]; then
-        	session_suspend $SESSID
-        	if [ $? -ne 0 ]; then
+                session_suspend $SESSID
+                if [ $? -ne 0 ]; then
                     session_switch_status $SESSID 3
                     session_check_status $SESSID 3
                     return $?
@@ -249,8 +246,8 @@ session_check_status() {
             local ready_t1=`date +%s`
             local diff=$(( $ready_t1 - $ready_t0 ))
             if [ $diff -gt $timeout ]; then
-	        log_ERROR "No ssh connection since $timeout seconds"
-	        session_switch_status $SESSID 3
+                log_ERROR "No ssh connection since $timeout seconds"
+                session_switch_status $SESSID 3
                 session_check_status $SESSID 3
                 return $?
             fi
@@ -259,7 +256,7 @@ session_check_status() {
                 touch ${SESSID_DIR}/private/ssh_connected
                 touch ${SESSID_DIR}/private/running
             fi
-	fi
+        fi
 
         application_loop $SESSID
     fi
@@ -274,18 +271,18 @@ garbage_collector() {
     # (runasap=0) since 60 second
     #
     for SESSID in $(sessions_get_active); do
-	local SESSID_DIR=$SPOOL/sessions/$SESSID
-	local RUNASAP=`cat ${SESSID_DIR}/infos/status`
-	[ $RUNASAP -ne 0 ] && continue
+        local SESSID_DIR=$SPOOL/sessions/$SESSID
+        local RUNASAP=`cat ${SESSID_DIR}/infos/status`
+        [ $RUNASAP -ne 0 ] && continue
 
-	local now=`date +%s`
-	local runasap=`stat -c "%Z" ${SESSID_DIR}/infos/status`
-	local diff=$(( $now - $runasap ))
+        local now=`date +%s`
+        local runasap=`stat -c "%Z" ${SESSID_DIR}/infos/status`
+        local diff=$(( $now - $runasap ))
 
-	if [ $diff -gt 60 ]; then
-	    log_WARN "garbage_collector: found non-used session '$SESSID' -> remove it"
-	    session_remove $SESSID
-	fi
+        if [ $diff -gt 60 ]; then
+            log_WARN "garbage_collector: found non-used session '$SESSID' -> remove it"
+            session_remove $SESSID
+        fi
     done
 }
 
@@ -293,76 +290,75 @@ loop() {
     # check if the system is clean before to start
     system_clean
     if [ $? -ne 0 ]; then
-	log_ERROR "Remaining garbage in home dirs, cannot start."
-	webservices_server_broken
-	exit 1
+        log_ERROR "Remaining garbage in home dirs, cannot start."
+        webservices_server_broken
+        exit 1
     fi
 
     trap 'stop' KILL EXIT
     spool_clean
     spool_init
 
-	if [ ! -d /tmp/.X11-unix ]; then
+    if [ ! -d /tmp/.X11-unix ]; then
             mkdir /tmp/.X11-unix
-	fi
-	chmod a+rwxt /tmp/.X11-unix
+    fi
+    chmod a+rwxt /tmp/.X11-unix
 
-	if [ ! -d /tmp/.ICE-unix ]; then
-	    mkdir /tmp/.ICE-unix
-	fi
-	chmod a+rwxt /tmp/.ICE-unix
+    if [ ! -d /tmp/.ICE-unix ]; then
+        mkdir /tmp/.ICE-unix
+    fi
+    chmod a+rwxt /tmp/.ICE-unix
 
     # Give availables application to the sessionmanager
     # webservices_available_application || exit 1
     webservices_server_ready
     if [ $? -ne 0 ]; then
-	log_ERROR "The request send to the Session manager to say hello returned an error, exiting"
-	exit 1
+        log_ERROR "The request send to the Session manager to say hello returned an error, exiting"
+        exit 1
     fi
     apt_daemon &
     PID_WATCH=$!
 
     local t0=`date +%s`
     while [ 1 ]; do
-	cache_build
+        cache_build
 
-	local t1=`date +%s`
-	local diff=$(( $t1 - $t0 ))
-	if [ $diff -gt 60 ]; then
-	    webservices_system_monitoring
-	    log_DEBUG "monitoring send result: $?"
-	    local t0=`date +%s`
-	fi
+        local t1=`date +%s`
+        local diff=$(( $t1 - $t0 ))
+        if [ $diff -gt 60 ]; then
+            webservices_system_monitoring
+            log_DEBUG "monitoring send result: $?"
+            local t0=`date +%s`
+        fi
 
-	local active=$(sessions_get_active)
-	local tocreate=$(sessions_get_to_create)
-	local nb_active=$(echo $active | wc -w)
-	local nb_tocreate=$(echo $tocreate | wc -w)
-	if [ $nb_active -gt 0 ] || [ $nb_tocreate -gt 0 ]; then
+        local active=$(sessions_get_active)
+        local tocreate=$(sessions_get_to_create)
+        local nb_active=$(echo $active | wc -w)
+        local nb_tocreate=$(echo $tocreate | wc -w)
+        if [ $nb_active -gt 0 ] || [ $nb_tocreate -gt 0 ]; then
             log_DEBUG "loop active session: ${nb_active}, to create: ${nb_tocreate}"
-	fi
+        fi
 
-
-	check_cpulimit
+        check_cpulimit
 
         # Check session to create
-	for SESSID in $(sessions_get_to_create); do
-	    log_INFO "creating session $SESSID"
-	    session_init $SESSID
-	    rm $SPOOL/sessions2create/$SESSID
-	done
+        for SESSID in $(sessions_get_to_create); do
+            log_INFO "creating session $SESSID"
+            session_init $SESSID
+            rm $SPOOL/sessions2create/$SESSID
+        done
 
         # For each session ...
-	for SESSID in $(sessions_get_active); do
-	    log_DEBUG "Ses "$SESSID
-	    session_check_status $SESSID
-	    ret=$?
-	
-	    [ $ret -eq 1 ] && session_remove $SESSID
-	done
+        for SESSID in $(sessions_get_active); do
+            log_DEBUG "Ses "$SESSID
+            session_check_status $SESSID
+            ret=$?
 
-	garbage_collector
-	sleep 1
+            [ $ret -eq 1 ] && session_remove $SESSID
+        done
+
+        garbage_collector
+        sleep 1
     done
 }
 
@@ -380,15 +376,15 @@ stop() {
     killall -q -9 kblankscrn.kss
 
     for SESSID in $(sessions_get_active); do
-	local SESSID_DIR=$SPOOL/sessions/$SESSID
-	local RUNASAP=`cat ${SESSID_DIR}/infos/status`
-	if [ $RUNASAP -ne 0 ]; then
-	    session_purge $SESSID
-	fi
+        local SESSID_DIR=$SPOOL/sessions/$SESSID
+        local RUNASAP=`cat ${SESSID_DIR}/infos/status`
+        if [ $RUNASAP -ne 0 ]; then
+            session_purge $SESSID
+        fi
 
-	session_remove $SESSID
+        session_remove $SESSID
     done
-    
+
     system_clean
     # if not 0 => broken !
 
@@ -453,17 +449,18 @@ fi
 eval set -- "$ARGS"
 while true ; do
     case "$1" in
-	-d|--daemonize)
-	    DAEMON=1
-	    shift;;
-	-p|--pid)
-	    PID_FILE=$2
-	    shift 2 ;;
-	--)
-	    shift ; break ;;
-	*)
-	    echo "Internal error!" 
-	    exit 1 ;;
+        -d|--daemonize)
+            DAEMON=1
+            shift;;
+        -p|--pid)
+            PID_FILE=$2
+            shift 2;;
+        --)
+            shift;
+            break ;;
+        *)
+            echo "Internal error!" 
+            exit 1;;
     esac
 done
 
