Bugfix: remove also group in system_clean
git-svn-id: file:///home/code/svn/ovd/branches/2.5@3135 2b2718be-6ee5-4ec5-ad1a-3fa14f9c7ca3

diff --git a/ApplicationServer/daemon/ulteo-ovdd b/ApplicationServer/daemon/ulteo-ovdd
--- a/ApplicationServer/daemon/ulteo-ovdd
+++ b/ApplicationServer/daemon/ulteo-ovdd
@@ -34,6 +34,16 @@ system_clean() {
             local fail=1
         fi
     done
+
+    for group in $(get_real_group); do
+        log_INFO "system_clean: existing group '$group': groupdel it"
+        groupdel $group
+        if [ $? !=  0 ]; then
+            log_ERROR "system_clean: unable to remove group '$group'"
+            local fail=1
+        fi
+    done
+
     [ $fail = 0 ] || return $fail
 
     # Ensure no user homes are left:
