put an error message when the ready message is send
git-svn-id: file:///home/code/svn/ovd/trunk@325 2b2718be-6ee5-4ec5-ad1a-3fa14f9c7ca3

diff --git a/ApplicationServer/daemon/ulteo-ovdd b/ApplicationServer/daemon/ulteo-ovdd
--- a/ApplicationServer/daemon/ulteo-ovdd
+++ b/ApplicationServer/daemon/ulteo-ovdd
@@ -357,7 +357,11 @@ loop() {
 
     # Give availables application to the sessionmanager
     # webservices_available_application || exit 1
-    webservices_server_ready || exit 1
+    webservices_server_ready
+    if [ $? -ne 0 ]; then
+	log_ERROR "The request send to the Session manager to say hello returned an error, exiting"
+	exit 1
+    fi
     apt_daemon &
     PID_WATCH=$!
 
